Sparse IFDS solver
secure-software-engineering/FlowDroid pull request #628
Opened 2023-06-29 08:01 UTC by timll

2023-06-29 14:50 UTC, StevenArzt requested changes

2023-06-29 14:50 UTC, StevenArzt commented on soot-infoflow/src/soot/jimple/infoflow/InfoflowConfiguration.java
> +		private SparsePropagationStrategy sparsePropagationStrategy = SparsePropagationStrategy.Precise;
Hat diese Klasse nicht auch noch ein ``hashCode()`` und ``equals()``, das man anpassen müsste?

2023-06-29 14:50 UTC, StevenArzt commented on soot-infoflow/src/soot/jimple/infoflow/solver/sparseSolver/propagation/AbstractSparsePropagation.java
> +            SootMethod turnM;
Ich würde hier schon aussteigen, falls ``forwardFlowSensitivity = true``

2023-06-29 14:50 UTC, StevenArzt commented on soot-infoflow/src/soot/jimple/infoflow/solver/sparseSolver/propagation/SimpleSparsePropagation.java
> +            return stmt.containsInvokeExpr() || (stmt.containsFieldRef() && stmt.getFieldRef().getField() == field);
Wieso wird hier nicht geprüft, ob es ein statisches Feld ist?

2023-06-30 07:59 UTC, timll commented on soot-infoflow/src/soot/jimple/infoflow/solver/sparseSolver/propagation/SimpleSparsePropagation.java
> +            return stmt.containsInvokeExpr() || (stmt.containsFieldRef() && stmt.getFieldRef().getField() == field);
Jedes `SootField` hat Name, Typ, Declaring Class und Modifiers wie static als Felder. Daher kann bei referential equality doch auch nur true herauskommen, wenn es wirklich das gleiche Feld ist. Und der Constructor stellt sicher, dass `field` definitiv static ist.

2023-06-30 08:04 UTC, StevenArzt approved these changes

2023-06-30 08:04 UTC, merged