FlowDroid: Clears für Setter nachtragen
secure-software-engineering/FlowDroid pull request #749
Opened 2024-06-17 13:50 UTC by iricarte

- Clears für mehrere Setters.
- Wichtige Annahme: Nur Setters mit Signatur 'void setX' haben Clear-Einträge bekommen. Setters, die bereits Clears hatten, wurden ignoriert.

2024-06-17 14:16 UTC, StevenArzt requested changes

2024-06-17 14:16 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/org.xml.sax.XMLReader.xml
> +				<clear sourceSinkType="Field"
Da ist eine Map-artige Struktur. Wenn ein Wert geschrieben wird, kannst du nicht alle anderen Werte ebenfalls wegwerfen. Schau mal in die ``java.util.Map``, wie das dort gemacht wird. Vermutlich fehlt hier einfach ein Constraint.

2024-06-17 14:16 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.util.concurrent.atomic.AtomicReferenceArray.xml
> +			<clears>
Du setzt ein Element in einem Array. Deswegen kannst du nicht alle Taints auf dem Array wegwerfen.

2024-06-17 14:16 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.util.ListIterator.xml
> +				<clear sourceSinkType="Field" AccessPath="[java.util.Iterator: java.lang.Object[] innerArray]"
Ein Element in einem Iterator zu ändern darf nicht die Taints von allen anderen Elementen in der zugrundeliegenden Collection entfernen.

2024-06-17 14:16 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/android.util.SparseArray.xml
> +            	<clear sourceSinkType="Field" BaseType="android.util.SparseArray"
Hier fehlt ein Constraint. Du kannst nicht alle Taints von einem Array löschen, wenn einzelnes Element überschrieben wird.

2024-06-17 14:16 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/android.util.JsonWriter.xml
> +			<clears>
Prüfe noch einmal, ob diese Methode wirklich die ganze Daten im Writer überschreibt. Ich habe da Zweifel.

2024-08-06 14:22 UTC, StevenArzt requested changes

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/android.graphics.Bitmap.xml
> +            	<clear sourceSinkType="Field" BaseType="android.graphics.Bitmap"
Das ist drei Mal drin, was keinen Sinn ergibt. Zudem ist es auch nicht sinnvoll, alle Taints auf der Bitmap zu clearen, wenn eine Koordinate überschrieben wird.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/android.graphics.Bitmap.xml
> +            	<clear sourceSinkType="Field" BaseType="android.graphics.Bitmap"
Die ganze Bitmap zu clearen wenn ein Teil davon überschrieben wird ist nicht sinnvoll

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/android.util.SparseArray.xml
> +                        isAlias="true" />
Können Clears Aliase haben? Da ist mir die Semantik gerade nicht klar.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/jdk.internal.misc.Unsafe.xml
> +			<clears>
Da wir nicht wissen, welcher Teil vom Speicher überschrieben wird, würde hier nicht clearen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/jdk.internal.misc.Unsafe.xml
> +			<clears>
Da wir nicht wissen, welcher Teil vom Speicher überschrieben wird, würde hier nicht clearen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/sun.misc.Unsafe.xml
> +			<clears>
Da wir nicht wissen, welcher Teil vom Speicher überschrieben wird, würde hier nicht clearen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/sun.misc.Unsafe.xml
> +		<clears>
Da wir nicht wissen, welcher Teil vom Speicher überschrieben wird, würde hier nicht clearen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.lang.StringBuilder.xml
> +			<clears>
Hier wird nur ein einzelner Character ersetzt. Da können wir nicht den Taint von allen Characters löschen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.lang.reflect.Array.xml
> +			<clears>
Es wird nur ein Element des Arrays überschrieben. Deshalb können wir nicht alle Taints vom gesamtem Array entfernen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.lang.reflect.Array.xml
> +			<clears>
Es wird nur ein Element des Arrays überschrieben. Deshalb können wir nicht alle Taints vom gesamtem Array entfernen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.lang.reflect.Array.xml
> +				<clear sourceSinkType="Parameter" ParameterIndex="0" />
Es wird nur ein Element des Arrays überschrieben. Deshalb können wir nicht alle Taints vom gesamtem Array entfernen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.lang.reflect.Array.xml
> +				<clear sourceSinkType="Parameter" ParameterIndex="0" />
Es wird nur ein Element des Arrays überschrieben. Deshalb können wir nicht alle Taints vom gesamtem Array entfernen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.lang.reflect.Array.xml
> +				<clear sourceSinkType="Parameter" ParameterIndex="0" />
Es wird nur ein Element des Arrays überschrieben. Deshalb können wir nicht alle Taints vom gesamtem Array entfernen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.lang.reflect.Array.xml
> +				<clear sourceSinkType="Parameter" ParameterIndex="0" />
Es wird nur ein Element des Arrays überschrieben. Deshalb können wir nicht alle Taints vom gesamtem Array entfernen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.lang.reflect.Array.xml
> +				<clear sourceSinkType="Parameter" ParameterIndex="0" />
Es wird nur ein Element des Arrays überschrieben. Deshalb können wir nicht alle Taints vom gesamtem Array entfernen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.lang.reflect.Array.xml
> +				<clear sourceSinkType="Parameter" ParameterIndex="0" />
Es wird nur ein Element des Arrays überschrieben. Deshalb können wir nicht alle Taints vom gesamtem Array entfernen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.lang.reflect.Array.xml
> +				<clear sourceSinkType="Parameter" ParameterIndex="0" />
Es wird nur ein Element des Arrays überschrieben. Deshalb können wir nicht alle Taints vom gesamtem Array entfernen.

2024-08-06 14:22 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/java.lang.StringBuffer.xml
> +				<clear sourceSinkType="Field"
Es wird nur ein einzelnes Zeichen ersetzt. Da können wir nicht alle Taints auf dem gesamten StringBuffer entfernen.

2024-08-07 11:20 UTC, iricarte commented on soot-infoflow-summaries/summariesManual/android.graphics.Bitmap.xml
> +            	<clear sourceSinkType="Field" BaseType="android.graphics.Bitmap"
Dabei dann Constraints auf die Koordinaten hinzufügen, oder?

2024-08-07 12:04 UTC, StevenArzt commented on soot-infoflow-summaries/summariesManual/android.graphics.Bitmap.xml
> +            	<clear sourceSinkType="Field" BaseType="android.graphics.Bitmap"
Wir unterstützen bei den Constraints keine Bedingungen über mehrere Parameter hinweg. Der Constraint müsste für das Paar ´´(x,y)`` zutreffen und das kann unsere Implementierung nicht. Also müssen wir hier über-approximieren und auf den Clear verzichten.

2024-08-08 11:37 UTC, iricarte commented on soot-infoflow-summaries/summariesManual/android.util.SparseArray.xml
> +                        isAlias="true" />
Ich glaube schon. Analog zu put(java.lang.Object,java.lang.Object) in Map.

2024-08-09 07:13 UTC, StevenArzt approved these changes

2024-08-09 07:13 UTC, merged